### ISSUE TITLE
[Whatsapp] Chrome error on first app opening, good on second start.

### ISSUE THREAD

**Issue by riptide981** [intersimone999/silos-apps#5]
On first start i get this message [https://imgur.com/HoRfrI7](url)
On second start everything seems ok.

```
 OS: Manjaro 20.2 Nibia
 Kernel: x86_64 Linux 5.9.11-3-MANJARO
 Uptime: 1h 42m
 Packages: 1319
 Shell: bash 5.0.18
 Resolution: 3600x1080
 DE: KDE 5.76.0 / Plasma 5.20.4
 WM: KWin
 GTK Theme: Breath-Dark [GTK2/3]
 Icon Theme: breath2-dark
 Disk: 296G / 520G (58%)
 CPU: AMD Phenom II X6 1090T @ 6x 3.2GHz
 GPU: NV92
 RAM: 3918MiB / 7957MiB
```

**Comment by Xystel** [comment]
Can confirm this issue with WhatsApp Plugin. Didn't knew that it works when I start it a second time.

I think I didn't had this issue a time before. But a few days ago I've got a Python upgrade from 3.8 to 3.9. I'm not sure but maybe it is a Python 3.9 related bug?

When I run ``silo -a whatsapp`` from terminal I get following exception:
```
 Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/pyqtws/plugin/TrayIcon.py", line 60, in __run_thread
    self.tray_icon.run()
  File "/usr/lib/python3.9/site-packages/pystray/_base.py", line 192, in run
    self._run()
  File "/usr/lib/python3.9/site-packages/pystray/_util/gtk.py", line 68, in _run
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "/usr/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```
My OS:
```
OS: Arch Linux x86_64
Kernel: 5.9.14-arch1-1
Shell: zsh 5.8
DE: Plasma 5.20.4
WM: KWin
CPU: Intel i7-2600K (8) @ 5.900GHz
GPU: NVIDIA GeForce GTX 970
```

**Comment by RubenKelevra** [comment]
@Xystel is this still an issue? I can use whatsapp without ever seeing an error message. :)

**Comment by elig0n** [comment]
for me it's the other way around: it worked the first time until I pressed "Update Whatsapp" from then on it would display the message about needing Chrome 60+
